// Dashboard mock data — chart series, recent forecasts, sparklines, error histogram.
// Generated by the same algorithms as artifact 10 (Dashboard).

import {
  mulberry32, NOW, NOW_HOUR_ANCHOR,
  MONTH_SHORT_UK, DAY_SHORT_UK,
} from '../utils';

// ----------- Hourly consumption model (GW) -----------
// Diurnal + weekly + seasonal, anchored around May 2026.
function consumptionAtHour(date) {
  const h = date.getHours();
  const dow = date.getDay();
  const month = date.getMonth();
  let v;
  if (h < 5) v = 11.6;
  else if (h < 8) v = 13.0 + (h - 5) * 0.9;
  else if (h < 11) v = 15.4 + Math.sin(((h - 8) / 3) * Math.PI) * 0.6;
  else if (h < 16) v = 13.8 + Math.sin(((h - 11) / 5) * Math.PI) * -0.4;
  else if (h < 22) v = 15.2 + Math.sin(((h - 16) / 6) * Math.PI) * 1.8;
  else v = 13.6 - (h - 22) * 0.5;
  if (dow === 0 || dow === 6) v -= 1.7;
  const seasonal = 3.2 * Math.cos(((month - 0) / 12) * 2 * Math.PI);
  v += seasonal * 0.55;
  return v;
}

// ----------- 24h window: -18h..+5h around NOW -----------
function generate24h() {
  const rand = mulberry32(101);
  const points = [];
  for (let i = -18; i <= 5; i++) {
    const d = new Date(NOW_HOUR_ANCHOR.getTime() + i * 3600_000);
    const base = consumptionAtHour(d);
    const noise = (rand() - 0.5) * 0.45;
    const actual = base + noise;
    const isFuture = i > 0;
    const forecast = base + (rand() - 0.5) * 0.25;
    points.push({
      name: String(d.getHours()).padStart(2, '0') + ':00',
      isoDate: d.toISOString(),
      hour: d.getHours(),
      day: d.getDay(),
      fact: isFuture ? null : +actual.toFixed(2),
      forecast: i >= -2 ? +forecast.toFixed(2) : null,
      lowerBound: i >= -2 ? +(forecast - 0.35).toFixed(2) : null,
      upperBound: i >= -2 ? +(forecast + 0.35).toFixed(2) : null,
      isFuture,
    });
  }
  return points;
}

// ----------- 7d window: 168 points (hourly), -5d..+2d -----------
function generate7d() {
  const rand = mulberry32(202);
  const points = [];
  const start = new Date(NOW_HOUR_ANCHOR.getTime() - 5 * 24 * 3600_000);
  for (let i = 0; i < 168; i++) {
    const d = new Date(start.getTime() + i * 3600_000);
    const base = consumptionAtHour(d);
    const noise = (rand() - 0.5) * 0.55;
    const isFuture = d > NOW_HOUR_ANCHOR;
    const fact = isFuture ? null : +(base + noise).toFixed(2);
    const fc = +(base + (rand() - 0.5) * 0.3).toFixed(2);
    const showFc = d.getTime() >= NOW_HOUR_ANCHOR.getTime() - 24 * 3600_000;
    const showLabel = d.getHours() === 12;
    points.push({
      name: showLabel ? DAY_SHORT_UK[d.getDay()] : '',
      isoDate: d.toISOString(),
      hour: d.getHours(),
      day: d.getDay(),
      fact,
      forecast: showFc ? fc : null,
      lowerBound: showFc ? +(fc - 0.45).toFixed(2) : null,
      upperBound: showFc ? +(fc + 0.45).toFixed(2) : null,
      isFuture,
    });
  }
  return points;
}

// ----------- 30d daily averages -----------
function generate30d() {
  const rand = mulberry32(303);
  const points = [];
  const start = new Date(NOW_HOUR_ANCHOR.getTime() - 29 * 24 * 3600_000);
  for (let i = 0; i < 30; i++) {
    const d = new Date(start.getTime() + i * 24 * 3600_000);
    d.setHours(12, 0, 0, 0);
    let avg = 0;
    for (let h = 0; h < 24; h++) {
      const dd = new Date(d); dd.setHours(h);
      avg += consumptionAtHour(dd);
    }
    avg /= 24;
    avg += (rand() - 0.5) * 0.6;
    const isFuture = d > NOW;
    points.push({
      name: i % 4 === 0 ? `${d.getDate()} ${MONTH_SHORT_UK[d.getMonth()]}` : '',
      isoDate: d.toISOString(),
      fact: isFuture ? null : +avg.toFixed(2),
      forecast: null,
      lowerBound: null,
      upperBound: null,
      isFuture,
    });
  }
  return points;
}

// ----------- 90d daily averages -----------
function generate90d() {
  const rand = mulberry32(404);
  const points = [];
  const start = new Date(NOW_HOUR_ANCHOR.getTime() - 89 * 24 * 3600_000);
  for (let i = 0; i < 90; i++) {
    const d = new Date(start.getTime() + i * 24 * 3600_000);
    d.setHours(12, 0, 0, 0);
    let avg = 0;
    for (let h = 0; h < 24; h++) {
      const dd = new Date(d); dd.setHours(h);
      avg += consumptionAtHour(dd);
    }
    avg /= 24;
    avg += (rand() - 0.5) * 0.7;
    points.push({
      name: i % 14 === 0 ? `${d.getDate()} ${MONTH_SHORT_UK[d.getMonth()]}` : '',
      isoDate: d.toISOString(),
      fact: +avg.toFixed(2),
      forecast: null,
      lowerBound: null,
      upperBound: null,
    });
  }
  return points;
}

// ----------- 1y weekly averages -----------
function generate1y() {
  const rand = mulberry32(505);
  const points = [];
  const start = new Date(NOW_HOUR_ANCHOR.getTime() - 51 * 7 * 24 * 3600_000);
  for (let i = 0; i < 52; i++) {
    const d = new Date(start.getTime() + i * 7 * 24 * 3600_000);
    d.setHours(12, 0, 0, 0);
    let avg = 0;
    for (let h = 0; h < 24; h++) {
      const dd = new Date(d); dd.setHours(h);
      avg += consumptionAtHour(dd);
    }
    avg /= 24;
    avg += (rand() - 0.5) * 0.5;
    points.push({
      name: d.getDate() <= 7 ? `${MONTH_SHORT_UK[d.getMonth()]} ${String(d.getFullYear()).slice(-2)}` : '',
      isoDate: d.toISOString(),
      fact: +avg.toFixed(2),
      forecast: null,
      lowerBound: null,
      upperBound: null,
    });
  }
  return points;
}

export const CHART_DATA = {
  '24h': generate24h(),
  '7d': generate7d(),
  '30d': generate30d(),
  '90d': generate90d(),
  '1y': generate1y(),
};

export const PERIOD_OPTIONS = [
  { id: '24h', label: '24 години' },
  { id: '7d',  label: '7 днів' },
  { id: '30d', label: '30 днів' },
  { id: '90d', label: '90 днів' },
  { id: '1y',  label: '1 рік' },
];

export const PERIOD_SUMMARIES = {
  '24h': 'За добу: середнє 14,6 ГВт · пік 17,2 ГВт о 19:00',
  '7d':  'За тиждень: середнє 14,6 ГВт · пік 17,2 ГВт (середа 19:00)',
  '30d': 'За місяць: середнє 14,2 ГВт · максимум 18,1 ГВт · мінімум 9,8 ГВт',
  '90d': 'За 3 місяці: середнє 13,9 ГВт · максимум 18,8 ГВт · мінімум 9,4 ГВт',
  '1y':  'За рік: середнє 13,8 ГВт · зимовий пік 19,4 ГВт (січень) · літній мінімум 9,2 ГВт (липень)',
};

// "Now" index per period — for the reference line
export const NOW_REF_INDEX = {
  '24h': 18,
  '7d': 120,
  '30d': 29,
  '90d': 89,
  '1y': 51,
};

// Recent forecasts list on Dashboard
export const RECENT_FORECASTS = [
  { id: 'f1', dateLabel: '8 трав, 13:00', horizonLabel: '+1 год · авто',  value: 14.6, errorPercent: 0.8 },
  { id: 'f2', dateLabel: '8 трав, 12:00', horizonLabel: '+1 год · авто',  value: 14.2, errorPercent: 1.1 },
  { id: 'f3', dateLabel: '8 трав, 09:00', horizonLabel: '+24 год · ручн.', value: 15.4, errorPercent: 2.3 },
  { id: 'f4', dateLabel: '7 трав, 18:00', horizonLabel: '+1 год · авто',  value: 16.1, errorPercent: 0.5 },
  { id: 'f5', dateLabel: '7 трав, 12:00', horizonLabel: '+1 год · авто',  value: 14.9, errorPercent: 1.4 },
];

// ----------- Sparklines for rolling MAPE -----------
function genSparkline(seed, n, base = 2.1, amp = 0.4) {
  const rand = mulberry32(seed);
  const out = [];
  let v;
  for (let i = 0; i < n; i++) {
    v = base + (rand() - 0.5) * amp + Math.sin(i / (n / 4)) * 0.15;
    out.push(+v.toFixed(3));
  }
  return out;
}

export const SPARKLINE_24H = genSparkline(11, 24, 2.08, 0.35);
export const SPARKLINE_7D = genSparkline(22, 7, 2.14, 0.25);
export const SPARKLINE_30D = genSparkline(33, 30, 2.31, 0.5);

// ----------- Error distribution histogram -----------
function genErrorDistribution() {
  const buckets = [];
  for (let x = -5; x <= 5; x += 0.5) {
    const mu = 0.5, sigma = 1.8;
    const y = Math.exp(-((x - mu) ** 2) / (2 * sigma * sigma));
    const count = Math.round(y * 130 + (mulberry32(Math.floor((x + 5) * 10))() - 0.5) * 8);
    buckets.push({ bucket: x.toFixed(1), x, count: Math.max(0, count) });
  }
  return buckets;
}

export const ERROR_DISTRIBUTION = genErrorDistribution();
